apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-app-secret" .Chart.Name | quote }}
type: Opaque
data:
  secret_conf.json: {{ .Values.secret.secret_conf_json | b64enc  }}
  another.yaml: {{ .Values.secret.another_yaml | b64enc  }}
