apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name | quote }}
    spec:
      imagePullSecrets:
      - name: "registrysecret"
      volumes:
      - name: app-conf
        configMap:
          name: {{ printf "%s-app" .Chart.Name | quote }}
      - name: app-secrets
        secret:
          secretName: {{ printf "%s-app-secret" .Chart.Name | quote }}
      containers:
      - name: {{ .Chart.Name | quote }}
{{- include "resources_app" . | indent 8 }}
{{ tuple "go-conf-example" . | include "werf_container_image" | indent 8 }}
        securityContext:
          runAsUser: 40004
          allowPrivilegeEscalation: false
        command: [ "/app/go-conf-example" ]
        workingDir: "/app"
        volumeMounts:
        - name: app-conf
          mountPath: /app/configfiles
        - name: app-secrets
          mountPath: /app/secretfiles
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: GIN_MODE
          value: "debug"
{{ tuple "go-conf-example" . | include "werf_container_env" | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
  clusterIP: "None"
  ports:
  - name: http
    port: 8080
    protocol: TCP
